version: '3.6'

services:
  ws:
    build: ./ws
    ports:
      - "8081:8080"
    links:
      - ws-db

  ws-db:
    build: ./db
    expose:
      - "5432"
    ports:
      - "5433:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/