
package co.simplon.java.workshop.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CategoryDBService", targetNamespace = "http://soap.workshop.java.simplon.co/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CategoryDBService {


    /**
     * 
     * @param nameFilter
     * @return
     *     returns java.util.List<co.simplon.java.workshop.soap.FoodCategory>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFoodCategoryListByName", targetNamespace = "http://soap.workshop.java.simplon.co/", className = "co.simplon.java.workshop.soap.GetFoodCategoryListByName")
    @ResponseWrapper(localName = "getFoodCategoryListByNameResponse", targetNamespace = "http://soap.workshop.java.simplon.co/", className = "co.simplon.java.workshop.soap.GetFoodCategoryListByNameResponse")
    @Action(input = "http://soap.workshop.java.simplon.co/CategoryDBService/getFoodCategoryListByNameRequest", output = "http://soap.workshop.java.simplon.co/CategoryDBService/getFoodCategoryListByNameResponse")
    public List<FoodCategory> getFoodCategoryListByName(
        @WebParam(name = "nameFilter", targetNamespace = "")
        String nameFilter);

    /**
     * 
     * @param foodCategoryId
     * @return
     *     returns co.simplon.java.workshop.soap.FoodCategory
     */
    @WebMethod
    @WebResult(name = "FoodCategory", targetNamespace = "")
    @RequestWrapper(localName = "getFoodCategoryById", targetNamespace = "http://soap.workshop.java.simplon.co/", className = "co.simplon.java.workshop.soap.GetFoodCategoryById")
    @ResponseWrapper(localName = "getFoodCategoryByIdResponse", targetNamespace = "http://soap.workshop.java.simplon.co/", className = "co.simplon.java.workshop.soap.GetFoodCategoryByIdResponse")
    @Action(input = "http://soap.workshop.java.simplon.co/CategoryDBService/getFoodCategoryByIdRequest", output = "http://soap.workshop.java.simplon.co/CategoryDBService/getFoodCategoryByIdResponse")
    public FoodCategory getFoodCategoryById(
        @WebParam(name = "foodCategoryId", targetNamespace = "")
        int foodCategoryId);

    /**
     * 
     * @param categoryName
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createFoodCategory", targetNamespace = "http://soap.workshop.java.simplon.co/", className = "co.simplon.java.workshop.soap.CreateFoodCategory")
    @ResponseWrapper(localName = "createFoodCategoryResponse", targetNamespace = "http://soap.workshop.java.simplon.co/", className = "co.simplon.java.workshop.soap.CreateFoodCategoryResponse")
    @Action(input = "http://soap.workshop.java.simplon.co/CategoryDBService/createFoodCategoryRequest", output = "http://soap.workshop.java.simplon.co/CategoryDBService/createFoodCategoryResponse")
    public int createFoodCategory(
        @WebParam(name = "categoryName", targetNamespace = "")
        String categoryName);

}
