
package co.simplon.java.workshop.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CategoryDBService", targetNamespace = "http://soap.workshop.java.simplon.co/", wsdlLocation = "http://192.168.1.208:8081/soap-demo/categoryDBService?wsdl")
public class CategoryDBService_Service
    extends Service
{

    private final static URL CATEGORYDBSERVICE_WSDL_LOCATION;
    private final static WebServiceException CATEGORYDBSERVICE_EXCEPTION;
    private final static QName CATEGORYDBSERVICE_QNAME = new QName("http://soap.workshop.java.simplon.co/", "CategoryDBService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.208:8081/soap-demo/categoryDBService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CATEGORYDBSERVICE_WSDL_LOCATION = url;
        CATEGORYDBSERVICE_EXCEPTION = e;
    }

    public CategoryDBService_Service() {
        super(__getWsdlLocation(), CATEGORYDBSERVICE_QNAME);
    }

    public CategoryDBService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CATEGORYDBSERVICE_QNAME, features);
    }

    public CategoryDBService_Service(URL wsdlLocation) {
        super(wsdlLocation, CATEGORYDBSERVICE_QNAME);
    }

    public CategoryDBService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CATEGORYDBSERVICE_QNAME, features);
    }

    public CategoryDBService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CategoryDBService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CategoryDBService
     */
    @WebEndpoint(name = "CategoryDBServicePort")
    public CategoryDBService getCategoryDBServicePort() {
        return super.getPort(new QName("http://soap.workshop.java.simplon.co/", "CategoryDBServicePort"), CategoryDBService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CategoryDBService
     */
    @WebEndpoint(name = "CategoryDBServicePort")
    public CategoryDBService getCategoryDBServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.workshop.java.simplon.co/", "CategoryDBServicePort"), CategoryDBService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CATEGORYDBSERVICE_EXCEPTION!= null) {
            throw CATEGORYDBSERVICE_EXCEPTION;
        }
        return CATEGORYDBSERVICE_WSDL_LOCATION;
    }

}
