
package co.simplon.java.workshop.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FoodDBService", targetNamespace = "http://soap.workshop.java.simplon.co/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FoodDBService {


    /**
     * 
     * @param foodAttributeId
     * @return
     *     returns co.simplon.java.workshop.soap.FoodAttribute
     */
    @WebMethod
    @WebResult(name = "FoodAttribute", targetNamespace = "")
    @RequestWrapper(localName = "getFoodAttributeById", targetNamespace = "http://soap.workshop.java.simplon.co/", className = "co.simplon.java.workshop.soap.GetFoodAttributeById")
    @ResponseWrapper(localName = "getFoodAttributeByIdResponse", targetNamespace = "http://soap.workshop.java.simplon.co/", className = "co.simplon.java.workshop.soap.GetFoodAttributeByIdResponse")
    @Action(input = "http://soap.workshop.java.simplon.co/FoodDBService/getFoodAttributeByIdRequest", output = "http://soap.workshop.java.simplon.co/FoodDBService/getFoodAttributeByIdResponse")
    public FoodAttribute getFoodAttributeById(
        @WebParam(name = "foodAttributeId", targetNamespace = "")
        int foodAttributeId);

    /**
     * 
     * @param carb
     * @param prot
     * @param name
     * @param fat
     * @param categoryName
     * @param energy
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createFoodAttribute", targetNamespace = "http://soap.workshop.java.simplon.co/", className = "co.simplon.java.workshop.soap.CreateFoodAttribute")
    @ResponseWrapper(localName = "createFoodAttributeResponse", targetNamespace = "http://soap.workshop.java.simplon.co/", className = "co.simplon.java.workshop.soap.CreateFoodAttributeResponse")
    @Action(input = "http://soap.workshop.java.simplon.co/FoodDBService/createFoodAttributeRequest", output = "http://soap.workshop.java.simplon.co/FoodDBService/createFoodAttributeResponse")
    public int createFoodAttribute(
        @WebParam(name = "categoryName", targetNamespace = "")
        String categoryName,
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "energy", targetNamespace = "")
        int energy,
        @WebParam(name = "prot", targetNamespace = "")
        int prot,
        @WebParam(name = "fat", targetNamespace = "")
        int fat,
        @WebParam(name = "carb", targetNamespace = "")
        int carb);

    /**
     * 
     * @param nameFilter
     * @return
     *     returns java.util.List<co.simplon.java.workshop.soap.FoodAttribute>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFoodAttributeListByName", targetNamespace = "http://soap.workshop.java.simplon.co/", className = "co.simplon.java.workshop.soap.GetFoodAttributeListByName")
    @ResponseWrapper(localName = "getFoodAttributeListByNameResponse", targetNamespace = "http://soap.workshop.java.simplon.co/", className = "co.simplon.java.workshop.soap.GetFoodAttributeListByNameResponse")
    @Action(input = "http://soap.workshop.java.simplon.co/FoodDBService/getFoodAttributeListByNameRequest", output = "http://soap.workshop.java.simplon.co/FoodDBService/getFoodAttributeListByNameResponse")
    public List<FoodAttribute> getFoodAttributeListByName(
        @WebParam(name = "nameFilter", targetNamespace = "")
        String nameFilter);

}
